### ISSUE TITLE
5.0 subfolder create a undefined parent directory

### ISSUE THREAD

**Issue by sxdxyxy** [jlegewie/zotfile#268]
When I upgrade to 5.0 ( 5.2 has the same issue), when rename a file with configuration of %c, the rename process create a "undefined/"  folder pre to the path. I ask someone else, they have the same issue. 

e.g. If I want rename a file with the pattern as "/storage/%c", after the rename process, the result of rename turned to be "storage/undefined/%c".

I do not know where the problem lies, zotfile or Zotero configuration.

**Comment by benimadimben** [comment]
I have this exact same issue (reported on Zotero forum [here](https://forums.zotero.org/discussion/comment/273533/#Comment_273533)) - is this something that is likely to be retrospectively fixable? I'm continuing to build my library despite this "undefined" folder issue and worried that I'm going to lose that work once this is fixed...?

**Comment by benimadimben** [comment]
sorry if I'm unaware of protocol on these fora, but can I "bump" this to see if anyone has any suggestions / at least confirmation that this is an issue others are experiencing? I'm running Zotero 5.0-beta.182+d472752 with Zotfile 5.0.0b3 on Mac running Sierra 10.12.2, and my Zotfile renames to a library folder located in Dropbox. keen to get this issue sorted, or at least to know that I won't discover I've been wasting my time and will have to manually rename and refile everything...? Many thanks for any assistance.

**Comment by jlegewie** [comment]
Yes, it probably is an issue but I haven't tested it and I don't know when I will get to fixing it (not using the `%c` wildcard myself). When it get's fixed, you will have to move the files again using zotfile, which you can do by selecting them all and using the rename function.

**Comment by benimadimben** [comment]
thanks @jlegewie I appreciate the update. I suppose it must be an issue limited to the %c option, which is why not many other people have reported experiencing it...

**Comment by jlegewie** [comment]
This should be fixed in 5.0.3 (currently on GitHub and only for Zotero 5.x). Anyone want to check. 

Note that it's only fixed when you use the %c wildcard alone not when you combine it with other wildcards.

**Comment by greenstep1877** [comment]
Same problem here.I am using 5.0.4.

**Comment by jlegewie** [comment]
You are using the development version from GitHub (not the one under releases) and still have the problem?

**Comment by greenstep1877** [comment]
I am using the released version of Zotero (5.0.4) and zotfile (5.0.2). Both are downloaded from the official website. By the way, I am using Mac OS. There is a parent folder named "undefined".  I am setting the subfolder option as "%c".

**Comment by jlegewie** [comment]
This is only fixed in the development version. So no surprise that you have the problem.

**Comment by Niko72** [comment]
@jlegewie Thanks, it works great again!

**Comment by cpence** [comment]
Sorry to re-open a dead issue, but I get the same 'undefined' folder when using `%w` in a path on Zotfile 5.0.4.

**Comment by jlegewie** [comment]
Please provide more details. Exact settings, steps to reproduce. Also note that it's only fixed when you use the %c wildcard alone not when you combine it with other wildcards.

**Comment by kolotelo** [comment]
Dear @jlegewie 
I use MacOs 10.13.3 and Zotero 5.0.35.1 standalone. Zotfile is 5.0.6 (tried both downloaded from zotfile.com and the make as suggested above).
I followed the steps above and tried several changes including what was reported at Zoreto Forum: https://forums.zotero.org/discussion/63655/storage-folders-name-cusomization
and still getting "undefined" folder. What am I doing wrong?

**Comment by Xain3** [comment]
Dear @jlegewie ,
I'm currently encountering another occurrence of the the "undefined" issue for subfolders " %A/%a/ " (Initial/Author). It'd seem that the wildcard %c is not the only culprit out there.
I'm running ZotFiles 5.0.6 in Zotero 5.0.35.1, on a Mac with MacOS 10.13.3.

I hope this will help!

**Comment by jlegewie** [comment]
I am swamped with other things so don't really have time to work on zotfile. But this is on the top of the list and I will try to look into it. But no promises on timeline.

**Comment by jlegewie** [comment]
This should be fixed in the development version from github. At least the problem that Xain3 reported. Anyone can confirm?

IF you are still having the problem, post here with detailed steps to reproduce including your zotfile preferences.
