### ISSUE TITLE
`%b` for citation key in renaming format no longer works

### ISSUE THREAD

**Issue by postylem** [jlegewie/zotfile#661]
In ZotFile Preferences > Renaming rules, If I use `%b` in the renaming format, and press "Update" to previes, I just get `_`. In use, the file is just renamed `pdf`. Up until today, this used to work great, both in preview and in practice, the name would be the citation key, but today it (silently) stopped working. 

I found a previous discussion of this, but it seems to say it was fixed: #386 
Is this an issue with my setup somehow, or has the issue resurfaced?

----
Edit: add version info:

- Zotero v6.0.26, on macOS
- _ZotFile_ v5.1.2, updated July 24 2023
- _Better BibTex for Zotero_ v6.7.96, **updated Aug 1, 2023**

(Side note, I guess it might be helpful if there were an error message displayed when something like this happens, because I only found out about this after adding multiple files, and realizing none of them were being added successfully, perhaps due to the fact that the undesired filename "pdf" already was taken. I don't know if that's possible/practical for zotfile to display an error message somehow when renaming fails.)

**Comment by 1qzhworld** [comment]
I also experienced the same issue with the most recent versions of Zotfile and Better Bibtex in Zotero 6.0.26.

**Comment by kleinlennart** [comment]
Same here. Other renaming wildcards still work, just not the `%b`, so might indeed be an issue with BetterBibTeX and its [newest release](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.96) (v6.7.96, Aug 1).

**Comment by Blavenger3** [comment]
See also here: https://forums.zotero.org/discussion/106610/zotfile-suddenly-stopped-renaming-and-saving-as-pdf-file

**Comment by postylem** [comment]
Should be fixed after BBT dev's PR https://github.com/jlegewie/zotfile/pull/662 is merged

**Comment by jlegewie** [comment]
Just merged but you have to install the dev version from GitHub for now. There are also some changes to secure file before zotero 7 update but that code should only run when invoked through new option under Tools. Still not tested thoroughly so I only recommend that if you know what you are doing.

**Comment by dirfas832** [comment]
> can someone please provide the solution steps for someone who's not super technically proficient? 😅

Yes please - I would also appreciate this! 🙂

**Comment by postylem** [comment]
> > can someone please provide the solution steps for someone who's not super technically proficient? 😅
> 
> 
> 
> Yes please - I would also appreciate this! 🙂

Follow the instructions "To install the development version on github" in the [zotfile](https://github.com/jlegewie/zotfile) readme.

**Comment by galeee** [comment]
> > > can someone please provide the solution steps for someone who's not super technically proficient? 😅
> > 
> > 
> > Yes please - I would also appreciate this! 🙂
> 
> Follow the instructions "To install the development version on github" in the [zotfile](https://github.com/jlegewie/zotfile) readme.

awesome thank you!

**Comment by postylem** [comment]
> thank you!

note if you're on linux or macOS you can just use the makefile to create the required file by simply running 

```bash
make
```

after you extract the zip archive. 

just be sure you run it in the directory where the file names 'Makefile' is
